# Generated by Django 4.1 on 2022-09-20 01:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('perfil', models.CharField(max_length=45, verbose_name='Perfil')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=45, verbose_name='Telefono')),
                ('genero', models.CharField(max_length=45, verbose_name='Genero')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClasePaciente',
            fields=[
                ('id_Paciente', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=45, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=45, verbose_name='Ciudad')),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClaseSignosVitales',
            fields=[
                ('id_vitales', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.FloatField(default=0)),
                ('fRespiratoria', models.FloatField(default=0)),
                ('fCardiaca', models.FloatField(default=0)),
                ('temperatura', models.FloatField(default=0)),
                ('pArterial', models.FloatField(default=0)),
                ('glicemias', models.FloatField(default=0)),
                ('fechaHora', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SignosVitales', to='appHospital.clasepaciente')),
            ],
        ),
        migrations.CreateModel(
            name='clasePersonalSalud',
            fields=[
                ('id_PersonalSalud', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=45, verbose_name='Rol')),
                ('especialidad', models.CharField(max_length=45, verbose_name='Especialidad')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonaSalud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clasepaciente',
            name='id_PersonalSalud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='appHospital.clasepersonalsalud'),
        ),
        migrations.AddField(
            model_name='clasepaciente',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClaseHistoriaClinica',
            fields=[
                ('id_HistoriaClinica', models.AutoField(primary_key=True, serialize=False)),
                ('sugerencias', models.CharField(max_length=30, verbose_name='Sugerencias')),
                ('diagnostico', models.CharField(max_length=30, verbose_name='Diagnostico')),
                ('entorno', models.CharField(max_length=30, verbose_name='Entorno')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=30, verbose_name='Descripcion')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistoriaClinica', to='appHospital.clasepaciente')),
            ],
        ),
        migrations.CreateModel(
            name='ClaseFamiliar',
            fields=[
                ('id_Familiar', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45, verbose_name='Email')),
                ('parentezco', models.CharField(max_length=45, verbose_name='Parentezco')),
                ('id_Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Familiar', to='appHospital.clasepaciente')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
