# Generated by Django 4.1 on 2025-11-11 23:40

import appHospital.models.Paciente
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appHospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clasefamiliar",
            options={"verbose_name": "Familiar", "verbose_name_plural": "Familiares"},
        ),
        migrations.AlterModelOptions(
            name="clasehistoriaclinica",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Historia Clínica",
                "verbose_name_plural": "Historias Clínicas",
            },
        ),
        migrations.AlterModelOptions(
            name="clasepaciente",
            options={"verbose_name": "Paciente", "verbose_name_plural": "Pacientes"},
        ),
        migrations.AlterModelOptions(
            name="clasepersonalsalud",
            options={
                "verbose_name": "Personal de Salud",
                "verbose_name_plural": "Personal de Salud",
            },
        ),
        migrations.AlterModelOptions(
            name="clasesignosvitales",
            options={
                "ordering": ["-fechaHora"],
                "verbose_name": "Signos Vitales",
                "verbose_name_plural": "Signos Vitales",
            },
        ),
        migrations.AlterModelOptions(
            name="claseuser",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
        migrations.RemoveField(
            model_name="clasesignosvitales",
            name="pArterial",
        ),
        migrations.AddField(
            model_name="clasesignosvitales",
            name="pArterialDiastolica",
            field=models.FloatField(
                default=80,
                help_text="Presión arterial diastólica en mmHg (30-150)",
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(150),
                ],
                verbose_name="Presión Arterial Diastólica",
            ),
        ),
        migrations.AddField(
            model_name="clasesignosvitales",
            name="pArterialSistolica",
            field=models.FloatField(
                default=120,
                help_text="Presión arterial sistólica en mmHg (50-250)",
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(250),
                ],
                verbose_name="Presión Arterial Sistólica",
            ),
        ),
        migrations.AddField(
            model_name="claseuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AddField(
            model_name="claseuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Staff"),
        ),
        migrations.AlterField(
            model_name="clasefamiliar",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="clasefamiliar",
            name="parentezco",
            field=models.CharField(
                choices=[
                    ("padre", "Padre"),
                    ("madre", "Madre"),
                    ("hijo", "Hijo/a"),
                    ("hermano", "Hermano/a"),
                    ("conyuge", "Cónyuge"),
                    ("abuelo", "Abuelo/a"),
                    ("nieto", "Nieto/a"),
                    ("tio", "Tío/a"),
                    ("sobrino", "Sobrino/a"),
                    ("primo", "Primo/a"),
                    ("otro", "Otro"),
                ],
                max_length=45,
                verbose_name="Parentezco",
            ),
        ),
        migrations.AlterField(
            model_name="clasehistoriaclinica",
            name="descripcion",
            field=models.TextField(verbose_name="Descripcion"),
        ),
        migrations.AlterField(
            model_name="clasehistoriaclinica",
            name="diagnostico",
            field=models.TextField(verbose_name="Diagnostico"),
        ),
        migrations.AlterField(
            model_name="clasehistoriaclinica",
            name="entorno",
            field=models.TextField(blank=True, verbose_name="Entorno"),
        ),
        migrations.AlterField(
            model_name="clasehistoriaclinica",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="clasehistoriaclinica",
            name="sugerencias",
            field=models.TextField(blank=True, verbose_name="Sugerencias"),
        ),
        migrations.AlterField(
            model_name="clasepaciente",
            name="ciudad",
            field=models.CharField(max_length=100, verbose_name="Ciudad"),
        ),
        migrations.AlterField(
            model_name="clasepaciente",
            name="direccion",
            field=models.CharField(max_length=200, verbose_name="Direccion"),
        ),
        migrations.AlterField(
            model_name="clasepaciente",
            name="fecha_nacimiento",
            field=models.DateField(
                validators=[appHospital.models.Paciente.validar_edad]
            ),
        ),
        migrations.AlterField(
            model_name="clasepersonalsalud",
            name="especialidad",
            field=models.CharField(max_length=100, verbose_name="Especialidad"),
        ),
        migrations.AlterField(
            model_name="clasepersonalsalud",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="PersonalSalud",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clasepersonalsalud",
            name="rol",
            field=models.CharField(
                choices=[
                    ("medico", "Médico"),
                    ("enfermero", "Enfermero/a"),
                    ("terapeuta", "Terapeuta"),
                    ("auxiliar", "Auxiliar de Enfermería"),
                    ("fisioterapeuta", "Fisioterapeuta"),
                    ("nutricionista", "Nutricionista"),
                    ("psicologo", "Psicólogo/a"),
                ],
                max_length=45,
                verbose_name="Rol",
            ),
        ),
        migrations.AlterField(
            model_name="clasesignosvitales",
            name="fCardiaca",
            field=models.FloatField(
                help_text="Latidos por minuto (30-220)",
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(220),
                ],
                verbose_name="Frecuencia Cardíaca",
            ),
        ),
        migrations.AlterField(
            model_name="clasesignosvitales",
            name="fRespiratoria",
            field=models.FloatField(
                help_text="Respiraciones por minuto (5-60)",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="Frecuencia Respiratoria",
            ),
        ),
        migrations.AlterField(
            model_name="clasesignosvitales",
            name="fechaHora",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="clasesignosvitales",
            name="glicemias",
            field=models.FloatField(
                help_text="Nivel de glucosa en sangre en mg/dL (20-600)",
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(600),
                ],
                verbose_name="Glicemia (mg/dL)",
            ),
        ),
        migrations.AlterField(
            model_name="clasesignosvitales",
            name="oximetria",
            field=models.FloatField(
                help_text="Saturación de oxígeno en sangre (0-100%)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Oximetría (%)",
            ),
        ),
        migrations.AlterField(
            model_name="clasesignosvitales",
            name="temperatura",
            field=models.FloatField(
                help_text="Temperatura corporal en grados Celsius (30-45)",
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(45),
                ],
                verbose_name="Temperatura (°C)",
            ),
        ),
        migrations.AlterField(
            model_name="claseuser",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                max_length=1,
                verbose_name="Genero",
            ),
        ),
        migrations.AlterField(
            model_name="claseuser",
            name="perfil",
            field=models.CharField(
                choices=[
                    ("personal_salud", "Personal de Salud"),
                    ("familiar", "Familiar"),
                    ("paciente", "Paciente"),
                    ("admin", "Administrador"),
                ],
                max_length=45,
                verbose_name="Perfil",
            ),
        ),
    ]
