from .usuarioCreateView import ClaseCrearUsuarioView
from .FamiliarCreateView import ClaseCrearFamiliarView
from .PacienteCreateView import ClaseCrearPacienteView
from .PersonalSaludCreateView import ClaseCrearPersonalSaludView
from .SignosVitalesView import ClaseCrearSignosVitalesView
from .HistoriaClinicaView import ClaseCrearHistoriaClinicaView

from .PacienteDetail import ClasepacienteDetail
from .usuarioDetail import ClaseUserDetailView
from .PersonalSaludDetail import ClasePersonalSaludDetail
